import type { Metadata } from "next";
import "./globals.css";
import LeftSidebar from "@/components/sidebar/left";
import { cn } from "@/lib/utils";
import { fontSans } from "@/fonts";
import { ThemeProvider } from "@/components/theme-provider";
import RightSidebar from "@/components/sidebar/right";
import { TooltipProvider } from "@/components/ui/tooltip";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased flex flex-row flex-nowrap",
          fontSans.variable
        )}
      >
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <TooltipProvider>
            <div className="flex-1">{children}</div>
          </TooltipProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
